server:
  port: 9091
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/case_study
    username: root
    password: Anup1999@
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
  application:
    name: MOVIE-MS  

#Actuator configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
        

#Resilience4j configuration

resilience4j:
  circuitbreaker:
    instances:
      A-SERVICE:
       registerHealthIndicator: true
       eventConsumerBufferSize: 10
       failureRateThreshold: 50
       minimumNumberOfCalls: 5
       automaticTransitionFromOpenToHalfOpenEnabled: true
       waitDurationInOpenState: 5s
       permittedNumberOfCallsInHalfOpenState: 3
       slidingWindowSize: 10
       slidingWindowType: COUNT_BASED

ACTOR-MS:
  ribbon:
    eureka:
      enabled: false
    listOfServers: loacalhost:1000,localhost:2000,localhost:3000
    ServerListRefreshInterval: 15000      